services:
  api:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - MONGO_URI=mongodb://mongo:27017/realtime-api
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
